language: ruby
sudo: required
sudo: false
rvm:
  - 2.0.0
  - 2.1.1
  - 2.2.2
env:
  - DB=postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rspec spec
