language: ruby
sudo: required
rvm:
  - 2.0.0
  - 2.1.1
  - 2.2.2
script:
  - bundle exec rspec spec
before_script:
  - psql -c 'create database card_test_db;' -U me_test
  - cp config/database.yml.travis config/database.yml