language: ruby
rvm:
  - 2.1.1
  env:

  - DB=postgresql
script:
  - bundle exec rspec spec
postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database strano_test' -U postgres
