language: ruby
rvm:
  - 2.1.1
env:
  - DB=postgresql
script:
  - bundle exec rspec spec
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database card_test_db' -U postgres
