language: ruby
sudo: required
rvm:
  - 2.1.1
script:
  - bundle exec rspec spec
postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres
before_script:
  - "psql -c 'create database myapp_test;' -U postgres"
  - "rake db:migrate"