# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9f56638cc9da7866ff3b6c92a403922488f0dd02cffe4172adbfbc21e44d2671a1de8280a12a7cb91a9e4407bdf0b3413392f784ae83d4aaeabf472c3ea8194

test:
  secret_key_base: 1877c555f1e614296d61b44c41f7440721e7674ff0d5eb9b6df57e7a0fbc9b5648e59af51e3ecb910b79cab73bfe00b07b9a76cfcb180bd1fbbebdad8c4d808f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
